# @name user
#
# Requests for the User controller

# This file assumes you have already run the 'login' request from 'auth.http'
# to populate the {{accessToken}} variable.

@host = http://localhost
@port = 8090

# --- Variables for testing ---
@uuid_to_test = 1f357445-6f3c-490e-a3da-5ed1f18a117a

###
# @name createTunnel
# Create a new tunnel
POST {{host}}:{{port}}/api/tunnel
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "test"
}
# @lang=lua
> {%
  local json = vim.json.decode(response.body)
  client.global.set("uuid_to_test", json.uuid);
%}


###
# @name getTunnels
# Get all tunnels
GET {{host}}:{{port}}/api/tunnel
Authorization: Bearer {{accessToken}}

###
# @name deleteTunnel
# Deletea a specific tunnel
DELETE {{host}}:{{port}}/api/tunnel/{{uuid_to_test}}
Authorization: Bearer {{accessToken}}


###
# @name createDnsRoute
# Create a new dns route on the given tunnel
POST {{host}}:{{port}}/api/tunnel/dns/{{uuid_to_test}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "domain": "test.francvok.from.hr"
}

###
# @name getTunnel
# Get data for given tunnel
GET {{host}}:{{port}}/api/tunnel/{{uuid_to_test}}
Authorization: Bearer {{accessToken}}

###
# @name startTunnel
# Starts a tunnel as system process
PUT {{host}}:{{port}}/api/tunnel/{{uuid_to_test}}/start
Authorization: Bearer {{accessToken}}

###
# @name stopTunnel
# Stops a tunnel running as system process
PUT {{host}}:{{port}}/api/tunnel/{{uuid_to_test}}/stop
Authorization: Bearer {{accessToken}}


###
# @name restartTunnel
# Restarts a running tunnel with zero downtime
PUT {{host}}:{{port}}/api/tunnel/{{uuid_to_test}}/restart
Authorization: Bearer {{accessToken}}
