// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user and returns access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "loginDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenDto"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Generates a new access token using a valid refresh token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh Access Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenDto"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Generates a new access token using a valid refresh token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh Access Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenDto"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "return information about the server build, version, etc ...",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get server info",
                "responses": {
                    "200": {
                        "description": "Information about server",
                        "schema": {
                            "$ref": "#/definitions/dto.ServerInfoDto"
                        }
                    }
                }
            }
        },
        "/tunnel": {
            "get": {
                "description": "returns a list of all tunnels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Get a list of all tunnels",
                "responses": {
                    "200": {
                        "description": "List of tunnels",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TunnelDto"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "creates a new tunnel with given name and returns it",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "creates a new tunnel",
                "parameters": [
                    {
                        "description": "tunnel name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.nameDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Newly created tunnel",
                        "schema": {
                            "$ref": "#/definitions/dto.TunnelDto"
                        }
                    }
                }
            }
        },
        "/tunnel/dns/{id}": {
            "post": {
                "description": "Creates a new dns record on the tunnel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Creates a dns record on the tunnel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "dns domain",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.domainDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tunnel dns record created",
                        "schema": {
                            "$ref": "#/definitions/dto.TunnelDto"
                        }
                    }
                }
            }
        },
        "/tunnel/{id}": {
            "get": {
                "description": "Creates a new dns record on the tunnel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Creates a dns record on the tunnel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tunnel dns record created",
                        "schema": {
                            "$ref": "#/definitions/dto.TunnelDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "returns a list of all tunnels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Get a list of all tunnels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Tunnel deleted"
                    }
                }
            }
        },
        "/tunnel/{id}/restart": {
            "put": {
                "description": "restarts a tunnel with zero downtime",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "restarts a tunnel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Tunnel restarted"
                    }
                }
            }
        },
        "/tunnel/{id}/start": {
            "put": {
                "description": "stops a tunnel running as system proccess",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "stops a tunnel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tunnel id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Tunnel stopped"
                    }
                }
            }
        },
        "/user": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "Data for new user",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NewUserDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/all-users": {
            "get": {
                "description": "Fetches all users for superadmin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get all users for superadmin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserDto"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/my-data": {
            "get": {
                "description": "Fetches the currently logged-in user's data based on the JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get logged-in user data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/oib/{oib}": {
            "get": {
                "description": "get a user with oib",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user with oib",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user oib",
                        "name": "oib",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/search": {
            "get": {
                "description": "Performs a fuzzy search for users by first name, last name, or full name with similarity matching",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Search users by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserDto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/user/{uuid}": {
            "get": {
                "description": "get a user with uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user with uuid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user with new dat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid of user to be updated",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data for updating user",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "delete a user with uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user with uuid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.domainDto": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                }
            }
        },
        "controller.nameDto": {
            "type": "object"
        },
        "dto.DnsRecordDto": {
            "type": "object",
            "properties": {
                "commnet": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meta": {},
                "modified_on": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "proxiable": {
                    "type": "boolean"
                },
                "proxied": {
                    "type": "boolean"
                },
                "settings": {},
                "tags": {
                    "type": "array",
                    "items": {}
                },
                "ttl": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.NewUserDto": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user",
                        "superadmin"
                    ]
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "dto.ServerInfoDto": {
            "type": "object",
            "properties": {
                "build": {
                    "type": "string"
                },
                "buildTimestamp": {
                    "type": "string"
                },
                "commitHash": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.TokenDto": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "dto.TunnelDto": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "dnsRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DnsRecordDto"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UserDto": {
            "type": "object",
            "properties": {
                "policeToken": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
