# Stage 2: Build the backend
FROM golang:1.25 AS builder
WORKDIR /app

# Install Task runner
RUN go install github.com/go-task/task/v3/cmd/task@latest

# Copy Go module files and download dependencies first for caching
COPY go.mod go.sum ./

RUN go mod download

# Copy the entire server source code
COPY . .

ARG LDFLAGS

RUN go build -ldflags="$LDFLAGS" .

FROM cloudflare/cloudflared:latest

WORKDIR /

# Copy only the compiled binary from the builder stage
COPY --from=builder ./app/cloudflared-web-gui /cloudflared-web-gui

# Set the entrypoint for the container
ENTRYPOINT ["/cloudflared-web-gui"]

